alias cdp='cd ~/Projects'
alias cl='clear'
alias protoncheck='systemctl is-active --quiet NetworkManager && echo "NM OK" || echo "NM NOT RUNNING" \nprotonvpn --help | head'
alias lg='lazygit'
alias fcd='cd "$(fd --type d | fzf)"'
alias fgbr='git branch | grep -v "^\*" | fzf | xargs git checkout'
alias fgshow='git log --graph --color=always --format="%C(auto)%h%d %s %C(black)%C(bold)%cr" | fzf --ansi --no-sort --reverse --tiebreak=index --preview "f() { set -- \$(echo -- \$@ | grep -o \"[a-f0-9]\{7\}\"); [ \$# -eq 0 ] || git show --color=always \$1 ; }; f {}"'
alias fzb='fzf --preview '\''bat --color=always --style=numbers --line-range=:500 {}'\'''
alias gc='git clone'
alias v='nvim'
alias scn='sesh connect "$(sesh list --icons | tv --ansi | sed -E "s/\x1B\[[0-9;]*[A-Za-z]//g; s/^[^[:space:]]+[[:space:]]+//")"'
